PetPass/Controllers/PetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PetPass.Models;

namespace PetPass.Controllers
{
    [Authorize]
    public class PetsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PetsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pets
        public async Task<IActionResult> Index()
        {
            var identifier = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var pets = await _context.Pets.Where(p => p.UsuarioId.ToString() == identifier).ToListAsync();
            return View(pets);
        }

        // GET: Pets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pet = await _context.Pets
                .FirstOrDefaultAsync(m => m.IdPet == id);
            if (pet == null)
            {
                return NotFound();
            }

            return View(pet);
        }

        // GET: Pets/Details/5
        public async Task<IActionResult> Relatorio(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pet = await _context.Pets
                .Include(t => t.Vacinas)
                .FirstOrDefaultAsync(m => m.IdPet == id);
            if (pet == null)
            {
                return NotFound();
            }

            return View(pet);
        }

        // GET: Pets/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPet,NomePet,TipoPet,RacaPet,SexoPet,IdadePet,IdadePet2,PesoPet,DataNascPet,DataRegPet,FotoPet,UsuarioId")] Pet pet)
        {
            if (ModelState.IsValid)
            {
                var identifier = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                var user = await _context.Usuarios.Where(u => u.IdUsuario.ToString() == identifier).FirstOrDefaultAsync();
                pet.Usuario = user;
                _context.Add(pet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pet);
        }

        // GET: Pets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pet = await _context.Pets.FindAsync(id);
            if (pet == null)
            {
                return NotFound();
            }
            return View(pet);
        }

        // POST: Pets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPet,NomePet,TipoPet,RacaPet,SexoPet,IdadePet,IdadePet2,PesoPet,DataNascPet,DataRegPet,FotoPet,UsuarioId")] Pet pet)
        {
            if (id != pet.IdPet)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var identifier = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                    var user = await _context.Usuarios.Where(u => u.IdUsuario.ToString() == identifier).FirstOrDefaultAsync();
                    pet.Usuario = user;
                    _context.Update(pet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PetExists(pet.IdPet))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pet);
        }

        // GET: Pets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pet = await _context.Pets
                .FirstOrDefaultAsync(m => m.IdPet == id);
            if (pet == null)
            {
                return NotFound();
            }

            return View(pet);
        }

        // POST: Pets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pet = await _context.Pets.FindAsync(id);
            _context.Pets.Remove(pet);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PetExists(int id)
        {
            return _context.Pets.Any(e => e.IdPet == id);
        }
    }
}

PetPass/Controllers/VacinasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PetPass.Models;

namespace PetPass.Controllers
{
    [Authorize]
    public class VacinasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VacinasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Vacinas
        public async Task<IActionResult> Index()
        {
            var identifier = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var vacinas = await _context.Pets
                .Where(p => p.UsuarioId.ToString() == identifier)
                .SelectMany(p => p.Vacinas)
                .Include(v => v.Pet)
                .ToListAsync();
            return View(vacinas);
        }

        // GET: Vacinas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vacina = await _context.Vacinas
                .Include(v => v.Pet)
                .FirstOrDefaultAsync(m => m.IdVac == id);
            if (vacina == null)
            {
                return NotFound();
            }

            return View(vacina);
        }

        // GET: Vacinas/Create
        public async Task<IActionResult> Create()
        {
            var identifier = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var pets = await _context.Pets.Where(p => p.UsuarioId.ToString() == identifier).ToListAsync();
            ViewData["PetId"] = new SelectList(pets, "IdPet", "NomePet");
            return View();
        }

        // POST: Vacinas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdVac,Animal,Descricao,Idade_Aplicacao,Data_Aplicacao,Dose_Aplicada,PetId")] Vacina vacina)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vacina);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PetId"] = new SelectList(_context.Pets, "IdPet", "NomePet", vacina.PetId);
            return View(vacina);
        }

        // GET: Vacinas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vacina = await _context.Vacinas.FindAsync(id);
            if (vacina == null)
            {
                return NotFound();
            }
            var identifier = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var pets = await _context.Pets.Where(p => p.UsuarioId.ToString() == identifier).ToListAsync();
            ViewData["PetId"] = new SelectList(pets, "IdPet", "NomePet", vacina.PetId);
            return View(vacina);
        }

        // POST: Vacinas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdVac,Animal,Descricao,Idade_Aplicacao,Data_Aplicacao,Dose_Aplicada,PetId")] Vacina vacina)
        {
            if (id != vacina.IdVac)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vacina);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VacinaExists(vacina.IdVac))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vacina);
        }

        // GET: Vacinas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vacina = await _context.Vacinas
                .Include(v => v.Pet)
                .FirstOrDefaultAsync(m => m.IdVac == id);
            if (vacina == null)
            {
                return NotFound();
            }

            return View(vacina);
        }

        // POST: Vacinas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vacina = await _context.Vacinas.FindAsync(id);
            _context.Vacinas.Remove(vacina);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VacinaExists(int id)
        {
            return _context.Vacinas.Any(e => e.IdVac == id);
        }
    }
}

PetPass/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetPass</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/fontawesome/css/all.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light header border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><span style="color:white;font-weight:bold">Pet</span>Pass</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                     @if (User.Identity.IsAuthenticated)
                     {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pets" asp-action="Index">Pets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vacinas" asp-action="Index">Vacinas</a>
                        </li>
                      }

                    </ul>
                    <ul class="navbar-nav">

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark mr-3" asp-area="" asp-controller="Usuarios" asp-action="Edit">Olá, @User.Identity.Name</a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="btn" asp-area="" asp-controller="Usuarios" asp-action="Logout">Sair</a>
                            </li>
                        }

                        else
                        {
                            <li class="nav-item">
                                <a class="btn" asp-area="" asp-controller="Usuarios" asp-action="Login"><i class="fas fa-user mr-1"></i>Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2021 - PetPass - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>